### ISSUE TITLE
Convert to python3

### ISSUE THREAD

**Issue by ostasis** [BTCMarkets/api-client-python#3]
Hi,

Would someone be interested in converting (forking) this to python3.  I've tried 2to3 but I can't get it to authenticate.
Note it works fine as is for python2.  So it's not an issue with my keys.  The return from https://api.btcmarkets.net/account/balance is {'success': False, 'errorCode': 1, 'errorMessage': 'Authentication failed.'}

Thanks.

**Comment by robmcd** [comment]
After using 2to3 i was able to get it working by encoding the request data and signature string using utf-8.

`response = urllib.request.urlopen(request, data.encode("utf-8"))`

`signature = base64.b64encode(hmac.new(secret, stringToSign.encode("utf-8"), digestmod=hashlib.sha512).digest())`

**Comment by ostasis** [comment]
Thanks. robmcd.

**Comment by Tallthunder** [comment]
@ostasis @robmcd  Would you guys mind sharing the code you used? Alternatively, could you please comment on my authentication issue I posted #8 

Thanks again!
